### ISSUE TITLE
ACPI keys not working after sleep

### ISSUE THREAD

**Issue by sahdman** [RehabMan/OS-X-ACPI-Keyboard#2]
The Fn keys work fine after a fresh reboot, and I am able to make the brightness change from the keyboard. But after resume from sleep, they seem to stop working. Neither brightness works, not does sound up and down and I do not see any logs of ACPIDebug either. 

I am using a Lenovo ThinkPad E450 laptop.

**Comment by RehabMan** [comment]
Use the forums.  This is not the correct place to troubleshoot your mistake.
