### ISSUE TITLE
Brightness key has impact on volume (macOS 10.12.6)

### ISSUE THREAD

**Issue by hunterMG** [RehabMan/OS-X-ACPI-Keyboard#3]
I followed the guide of REAEME, but Fn+Up and Fn+Down both correspond to brightness up.
And Fn+Up also corresponds to volume down. The DSDT and kext I used are in the attach files.
(On my laptop, Fn+Up creates _Q12 EC query, Fn+Down creates _Q11 EC query.)
[Lenovo-G470.zip](https://github.com/RehabMan/OS-X-ACPI-Keyboard/files/1490759/Lenovo-G470.zip)

**Comment by RehabMan** [comment]
This is not the appropriate place to troubleshoot your mistake.
Please use the forums.
